version: '3.9'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: uptask-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: uptaskDB
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      MAIL_HOST:
      MAIL_PORT:
      MAIL_USER:
      MAIL_PASSWORD:
    volumes:
      - ./target:/app
    depends_on:
      - database
    command: ["java", "-jar", "/app/taskupv2-0.0.1-SNAPSHOT.jar"]

  database:
    image: postgres:16-alpine3.20
    container_name: uptask-db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: uptaskDB

volumes:
  postgres:
    external: false